### ISSUE TITLE
return: label, similarity

### ISSUE THREAD

**Issue by mztkenan** [policeme/chinese_bert_similarity#3]
请问这里label表示的什么意思

**Comment by xiongma** [comment]
this mean, the probability of second element  proximal 1 in return list, it means the two sentences are similar,  the probability of second element proximal 0 in return list, it means the two sentences are not similar.

**Comment by Morriaty-The-Murderer** [comment]
我理解是`label + similarity = 1`，但为什么我调换一下`text_a`和`text_b`，相似度就反了？
```python
>>> text_a = '技术侦查措施只能在立案后采取'
>>> text_b = '未立案不可以进行技术侦查'
>>> bs.predict([[text_a, text_b]])
array([[0.00942544, 0.99057454]], dtype=float32)
>>> bs.predict([[text_b, text_a]])
array([[0.9855568 , 0.01444321]], dtype=float32)
```

**Comment by xiongma** [comment]
如果有问题请到github上提issue
[image: image.png]

Morry Wang <notifications@github.com> 于2019年7月10日周三 下午2:49写道：
