### ISSUE TITLE
请问一下训练数据个格式是什么？

### ISSUE THREAD

**Issue by myboyliu** [policeme/chinese_bert_similarity#5]
是否分为3列：text_a,text_b,label,中间'\t'隔开？

**Comment by xiongma** [comment]
label,text_a,text_b


Cally Ma (马雄)
Chongqing University of Post and Telecommunications
Mobile: +86 15025700935
E-mail: mx15025700935@aliyun.com




------------------------------------------------------------------
发件人：刘博 <notifications@github.com>
发送时间：2019年11月8日(星期五) 13:35
收件人：policeme/chinese-bert-similarity <chinese-bert-similarity@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[policeme/chinese-bert-similarity] 请问一下训练数据个格式是什么？ (#5)

是否分为3列：text_a,text_b,label,中间'\t'隔开？
