### ISSUE TITLE
关于output_layer 的形式

### ISSUE THREAD

**Issue by Little-girl-1992** [policeme/chinese_bert_similarity#8]
我看你说output_layer 是最后4层的连接，可以提高1%，但是代码里缺没有用，不知道是为什么呢？
`output_layer = tf.concat([tf.squeeze(model.all_encoder_layers[i][:, 0:1, :], axis=1) for i in range(-4, 0, 1)], axis=-1)`

**Comment by policeme** [comment]
这个当时没有时间去训练，所以就没有尝试了，不好意思

**Comment by xiongma** [comment]
上传的这个模型是比较稳定的模型，而这个形式，还没有具体测试过，只是这样跑过，跑出来准确率比这个高，但是f1没看，不好意思。
